// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.PalindromeChecker
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("is_palindrome")]
        public bool IsPalindrome { get; set; }

        [JsonProperty("cleaned_text")]
        public string CleanedText { get; set; }

        [JsonProperty("reversed_text")]
        public string ReversedText { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("options")]
        public Options Options { get; set; }

        [JsonProperty("longest_palindrome_substring")]
        public string LongestPalindromeSubstring { get; set; }

        [JsonProperty("longest_palindrome_length")]
        public long LongestPalindromeLength { get; set; }
    }

    public partial class Options
    {
        [JsonProperty("ignore_case")]
        public bool IgnoreCase { get; set; }

        [JsonProperty("ignore_spaces")]
        public bool IgnoreSpaces { get; set; }

        [JsonProperty("ignore_punctuation")]
        public bool IgnorePunctuation { get; set; }
    }
}
